<a href="https://colab.research.google.com/github/unatardedemartes-a11y/ClassFiles/blob/main/S06_Actividad_02_ALGEBRALINEAL_275334.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Actividad calificada — Álgebra lineal con NumPy

**Programación para Analítica Descriptiva y Predictiva**
Maestría en Inteligencia Artificial y Analítica de Datos — UACJ

---

**Material de estudio previo:** `Material_Extra_Algebra_Lineal_NumPy.ipynb`. Revísalo antes de resolver esta actividad.

**Entrega:** individual, en este notebook de Google Colab (comparte el enlace con permiso de edición para el docente).
**Plazo:** 7 días naturales a partir de la publicación de esta actividad.
**Penalización por entrega tardía:** 5% por día, hasta 7 días; después de eso, la actividad no se recibe.
**Valor total:** 100 puntos.

### Herramientas permitidas

Esta actividad evalúa `np.linalg.norm()`, `np.dot()`/`@`, `np.linalg.det()`, `np.linalg.inv()`, `np.linalg.solve()`, y las operaciones de NumPy ya vistas en sesiones anteriores. No uses pandas ni scikit-learn.

### Cómo se evalúa

Cada ejercicio indica su valor en puntos. Se evalúa el resultado correcto **y** el uso de la función específica de `np.linalg` indicada en cada enunciado — calcular a mano una fórmula que NumPy ya resuelve (por ejemplo, programar la fórmula del determinante 2×2 en vez de usar `np.linalg.det()`) no obtiene el puntaje completo.

In [31]:
import numpy as np

## Parte 1 — Vectores: perfiles de producto

Una tienda en línea representa cada producto como un vector de 3 componentes: calificación de calidad, calificación de precio, y calificación de servicio (escala 1 a 5, donde 5 es mejor). Ejecuta la siguiente celda para cargar los tres productos — **no la modifiques**.

In [32]:
producto_A = np.array([4.5, 3.2, 5.0])
producto_B = np.array([4.0, 2.8, 4.7])
producto_C = np.array([1.0, 5.0, 1.2])

print(producto_A, producto_B, producto_C)

[4.5 3.2 5. ] [4.  2.8 4.7] [1.  5.  1.2]


---

### Ejercicio 1 — Norma de los vectores (10 pts)

Calcula la norma de `producto_A`, `producto_B` y `producto_C` usando `np.linalg.norm()`.

In [33]:
# Tu código aquí
norma_A = np.linalg.norm(producto_A)
norma_B = np.linalg.norm(producto_B)
norma_C = np.linalg.norm(producto_C)

print(f"Norma de producto_A: {norma_A}")
print(f"Norma de producto_B: {norma_B}")
print(f"Norma de producto_C: {norma_C}")


Norma de producto_A: 7.449161026585477
Norma de producto_B: 6.777167549942971
Norma de producto_C: 5.238320341483518


---

### Ejercicio 2 — Producto punto y ángulo (15 pts)

1. Calcula el producto punto entre `producto_A` y `producto_B`, y entre `producto_A` y `producto_C`, usando `np.dot()` o `@`.
2. Calcula el ángulo (en grados) entre `producto_A` y `producto_B`, y entre `producto_A` y `producto_C`.
3. Con base en los ángulos obtenidos, indica (en un comentario o celda de texto) cuál de los dos productos (`B` o `C`) es más similar a `producto_A`, y por qué el ángulo es el indicador correcto para esa comparación.

In [34]:
# Tu código aquí
dot_AB = np.dot(producto_A, producto_B)
dot_AC = np.dot(producto_A, producto_C)

print(f"AB = {dot_AB}")
print(f"AC = {dot_AC}")

#v · w = ||v|| × ||w|| × cos(θ)
#cos(θ) = (v · w) / (||v|| × ||w||)
#θ = arccos(cos(θ))
cos_AB = dot_AB / (norma_A * norma_B)
cos_AC = dot_AC / (norma_A * norma_C)

angulo_AB_rad = np.arccos(cos_AB)
angulo_AC_rad = np.arccos(cos_AC)

angulo_AB_grados = np.degrees(angulo_AB_rad)
angulo_AC_grados = np.degrees(angulo_AC_rad)
print(f"Angulo entre AB: {angulo_AB_grados}°")
print(f"Angulo entre AC: {angulo_AC_grados}°")

AB = 50.46
AC = 26.5
Angulo entre AB: 1.7745815839558179°
Angulo entre AC: 47.22509268261831°


En base a los resultados, el Producto B es mas similar al A que el producto C debido a que el angulo entre vectores indica que tan parecidas son las proporciones entre sus componentes

---

### Ejercicio 3 — Normalización (10 pts)

Normaliza los tres vectores (`producto_A`, `producto_B`, `producto_C`) para obtener sus vectores unitarios. Verifica, imprimiendo el resultado, que la norma de cada vector normalizado sea 1.

In [35]:
# Tu código aquí
vector_A_unitario = producto_A / norma_A
vector_B_unitario = producto_B / norma_B
vector_C_unitario = producto_C / norma_C

print(f"Norma de vector_A_unitario: {np.linalg.norm(vector_A_unitario)}")
print(f"Norma de vector_B_unitario: {np.linalg.norm(vector_B_unitario)}")
print(f"Norma de vector_C_unitario: {np.linalg.norm(vector_C_unitario)}")

Norma de vector_A_unitario: 1.0
Norma de vector_B_unitario: 1.0
Norma de vector_C_unitario: 1.0


## Parte 2 — Matrices: mezcla de insumos

Una fábrica de jugos combina dos insumos (concentrado de fruta y agua) en distintas proporciones para dos líneas de producto. La matriz `M` representa esas proporciones (filas = línea de producto, columnas = insumo), y `P` representa un ajuste de escala para una nueva presentación. Ejecuta la siguiente celda — **no la modifiques**.

In [36]:
M = np.array([[2, 1],
              [1, 3]])

P = np.array([[1.5, 0],
              [0, 2.0]])

print(M)
print(P)

[[2 1]
 [1 3]]
[[1.5 0. ]
 [0.  2. ]]


---

### Ejercicio 4 — Multiplicación matricial (15 pts)

1. Calcula `M * P` (elemento a elemento) y `M @ P` (multiplicación matricial). Los resultados son distintos — en un comentario o celda de texto, explica brevemente por qué.
2. Verifica que las formas sean compatibles: ¿cuál sería el resultado de `P @ M`? Calcúlalo y compáralo con `M @ P` — ¿da el mismo resultado?

In [37]:
# Tu código aquí
M_elemento = M * P  # cada posicion se multiplica independientemente
print(f"M * P: {M_elemento}")
print()
M_matricial = M @ P #cada elmento es una combinacion lineal de una fila y una columna
print(f"M @ P: {M_matricial}")
print()
PM_matricial = P @ M
print(f"P @ M: {PM_matricial}")
print()
print("Son resultador diferentes, la multiplicacion de matrices no es conmutativa")

M * P: [[3. 0.]
 [0. 6.]]

M @ P: [[3.  2. ]
 [1.5 6. ]]

P @ M: [[3.  1.5]
 [2.  6. ]]

Son resultador diferentes, la multiplicacion de matrices no es conmutativa


---

### Ejercicio 5 — Determinante e inversa (15 pts)

1. Calcula el determinante de `M` con `np.linalg.det()`. Confirma que `M` sí tiene inversa (determinante distinto de 0).
2. Calcula la inversa de `M` con `np.linalg.inv()`.
3. Verifica tu resultado calculando `M @ M_inv` — debe dar (aproximadamente) la matriz identidad.

In [38]:
# Tu código aquí
det_M = np.linalg.det(M)
print(f"det(M) = {det_M}")
if not np.isclose(det_M, 0):
    print("La matriz SI tiene inversa")
else:
    print("La matriz NO tiene inversa")
print()

M_inv = np.linalg.inv(M)
print("M_inv =")
print(M_inv)
print()

identidad = M @ M_inv
print("M @ M_inv =")
print(identidad)
print()

det(M) = 5.000000000000001
La matriz SI tiene inversa

M_inv =
[[ 0.6 -0.2]
 [-0.2  0.4]]

M @ M_inv =
[[ 1.00000000e+00  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00]]



---

### Ejercicio 6 — Sistema de ecuaciones (15 pts)

La fábrica necesita producir un lote que requiere en total 180 unidades de la línea 1 y 300 unidades de la línea 2, según las proporciones de `M`. Esto se representa como el sistema $Mx = b$, con:

```python
b = np.array([180, 300])
```

1. Resuelve el sistema con `np.linalg.solve()` para encontrar cuántas unidades de cada insumo (`x`) se necesitan.
2. Verifica tu solución multiplicando `M @ x` y confirmando que el resultado coincide con `b`.

In [39]:
b = np.array([180, 300])
# Tu código aquí

x = np.linalg.solve(M, b)
print(f"Solucion x = {x}")
print()
Mx = M @ x
print(f"M @ x = {Mx}")
print()
print("Son iguales")


Solucion x = [48. 84.]

M @ x = [180. 300.]

Son iguales


---

### Ejercicio 7 — Síntesis: distancia y similitud (20 pts)

Retomando los tres productos de la Parte 1:

1. Calcula la **distancia euclidiana** entre `producto_A` y `producto_B`, y entre `producto_A` y `producto_C`, usando la norma de la diferencia entre los vectores (`np.linalg.norm(a - b)`).
2. Calcula la **similitud coseno** entre los mismos pares — es el cociente que ya calculaste en el Ejercicio 2 antes de aplicar `arccos()`: $\frac{a \cdot b}{\|a\| \|b\|}$.
3. Con base en ambas métricas (distancia y similitud coseno), concluye en una cadena de texto impresa cuál producto (`B` o `C`) es más parecido a `producto_A`, y si ambas métricas coinciden en la misma conclusión.

In [40]:
# Tu código aquí
dist_AB = np.linalg.norm(producto_A - producto_B)
dist_AC = np.linalg.norm(producto_A - producto_C)
print(f"Distancia Euclidiana (A, B): {dist_AB}")
print(f"Distancia Euclidiana (A, C): {dist_AC}")
print()
print(f"Similitud coseno (A, B): {cos_AB}")
print(f"Similitud coseno (A, C): {cos_AC}")
print()
if dist_AB < dist_AC:
    similar_distancia = "B"
    menor_distancia = dist_AB
    mayor_distancia = dist_AC
else:
    similar_distancia = "C"
    menor_distancia = dist_AC
    mayor_distancia = dist_AB

if cos_AB > cos_AC:
    similar_coseno = "B"
    mayor_coseno = cos_AB
    menor_coseno = cos_AC
else:
    similar_coseno = "C"
    mayor_coseno = cos_AC
    menor_coseno = cos_AB
if similar_distancia == similar_coseno:
    print(f"El producto {similar_distancia} es mas parecido a producto_A según ambas metricas")
else:
    print(f"Las metricas no coinciden")
print()

Distancia Euclidiana (A, B): 0.7071067811865476
Distancia Euclidiana (A, C): 5.470831746635972

Similitud coseno (A, B): 0.9995203969214979
Similitud coseno (A, C): 0.6791199021706347

El producto B es mas parecido a producto_A según ambas metricas



---

## Antes de entregar

- Verifica que el notebook completo corra de principio a fin sin errores (**Entorno de ejecución → Ejecutar todas**).
- Confirma que no usaste pandas ni scikit-learn.
- Comparte el notebook con permiso de **edición** para el docente.